export const egyptGovernorates = [
        "Cairo",
        "Giza",
        "Alexandria",
        "Qalyubia",
        "Port Said",
        "Suez",
        "Dakahlia",
        "Sharqia",
        "Kalyubia",
        "Kafr El Sheikh",
        "Gharbia",
        "Monufia",
        "Beheira",
        "Ismailia",
        "Giza",
        "Beni Suef",
        "Faiyum",
        "Minya",
        "Asyut",
        "Sohag",
        "Qena",
        "Aswan",
        "Luxor",
        "Red Sea",
        "New Valley",
        "Matrouh",
        "North Sinai",
        "South Sinai"
    ];